"""Validate the final chapters manifest.

This gate protects the final folder from stale PDFs that were generated by an
older or family-inconsistent publication flow.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any, Mapping

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from scanner.canonical_publication_chapter_factory import CANONICAL_PUBLICATION_FLOW  # noqa: E402
from scanner.audit_final_family_shared_content import audit_manifest as audit_final_family_shared_content  # noqa: E402
from scanner.audit_publication_entrypoints import audit_publication_entrypoints  # noqa: E402
from scanner.audit_publication_style_v3 import audit_publication_style_v3  # noqa: E402
from scanner.audit_scanner_tradable_integrity import audit_manifest as audit_scanner_tradable_integrity  # noqa: E402
from scanner.publication_flow_contract import validate_publication_contract  # noqa: E402
from scanner.publication_semantic_contract import semantic_required, validate_publication_semantic_contract  # noqa: E402


DEFAULT_MANIFEST = Path("artifacts/final_chapters/final_chapters_manifest.json")
DEFAULT_TARGET_CALIBRATION_SUMMARY = Path(
    "artifacts/scanner_v2/final_chapters_target_calibration_audit/chapter_target_calibration_summary.json"
)
DEFAULT_CHAPTER_GOVERNANCE_MATRIX = Path("artifacts/final_chapters/governance/chapter_governance_matrix.json")
DEFAULT_TRADABLE_PREFLIGHT_MATRIX = Path("artifacts/final_chapters/governance/chapter_tradable_preflight_matrix.json")
TARGET_CALIBRATION_AUDIT_ID = "final_chapters_target_calibration_audit_v1"
DUAL_AXIS_CHAPTER_SCORING_ID = "dual_axis_chapter_scoring_v1"
TRADABLE_PREFLIGHT_MATRIX_ID = "tradable_preflight_matrix_v1"
APPROVED_FINAL_FLOWS = {
    "flag_family": CANONICAL_PUBLICATION_FLOW,
    "triangle_family": CANONICAL_PUBLICATION_FLOW,
    "double_pattern_family": CANONICAL_PUBLICATION_FLOW,
    "wedge_family": CANONICAL_PUBLICATION_FLOW,
    "cup_handle_family": CANONICAL_PUBLICATION_FLOW,
    "rectangle_family": CANONICAL_PUBLICATION_FLOW,
    "head_shoulders_family": CANONICAL_PUBLICATION_FLOW,
    "broadening_family": CANONICAL_PUBLICATION_FLOW,
    "measured_move_family": CANONICAL_PUBLICATION_FLOW,
    "scallop_family": CANONICAL_PUBLICATION_FLOW,
    "pipe_family": CANONICAL_PUBLICATION_FLOW,
    "horn_family": CANONICAL_PUBLICATION_FLOW,
    "diamond_family": CANONICAL_PUBLICATION_FLOW,
    "dead_cat_bounce_family": CANONICAL_PUBLICATION_FLOW,
    "three_peaks_valleys_family": CANONICAL_PUBLICATION_FLOW,
    "triple_family": CANONICAL_PUBLICATION_FLOW,
    "bump_and_run_family": CANONICAL_PUBLICATION_FLOW,
    "gap_family": CANONICAL_PUBLICATION_FLOW,
    "island_family": CANONICAL_PUBLICATION_FLOW,
    "rounding_family": CANONICAL_PUBLICATION_FLOW,
    "inside_day_family": CANONICAL_PUBLICATION_FLOW,
    "three_methods_family": CANONICAL_PUBLICATION_FLOW,
}


def _read_json(path: Path) -> Mapping[str, Any]:
    return json.loads(path.read_text(encoding="utf-8")) if path.exists() else {}


def validate_final_manifest(path: Path = DEFAULT_MANIFEST) -> dict[str, Any]:
    payload = _read_json(path)
    failures: list[dict[str, Any]] = []
    manifest_root = path.parent
    declared_pdfs: set[Path] = set()
    chapters = payload.get("chapters") if isinstance(payload.get("chapters"), list) else []
    for chapter in chapters:
        if not isinstance(chapter, Mapping):
            failures.append({"check": "chapter_shape", "detail": "chapter entry is not an object"})
            continue
        family = str(chapter.get("family") or "")
        status = str(chapter.get("status") or "")
        pdf = Path(str(chapter.get("pdf") or ""))
        if str(pdf):
            declared_pdfs.add(pdf)
        flow = str(chapter.get("publication_flow") or "")
        if status != "final":
            failures.append({"check": "status", "pattern_id": chapter.get("pattern_id"), "detail": f"unexpected status {status}"})
        if not pdf.exists():
            failures.append({"check": "pdf_exists", "pattern_id": chapter.get("pattern_id"), "detail": str(pdf)})
        expected_flow = APPROVED_FINAL_FLOWS.get(family)
        if not expected_flow:
            failures.append(
                {
                    "check": "approved_family_flow",
                    "pattern_id": chapter.get("pattern_id"),
                    "detail": f"family {family} has no approved final publication flow",
                }
            )
        elif flow != expected_flow:
            failures.append(
                {
                    "check": "publication_flow",
                    "pattern_id": chapter.get("pattern_id"),
                    "detail": f"expected {expected_flow}, got {flow}",
                }
            )
        contract = validate_publication_contract(chapter)
        if contract["status"] != "PASS":
            failures.extend(contract["failures"])
        if semantic_required(chapter):
            semantic_contract = validate_publication_semantic_contract(chapter)
            if semantic_contract["status"] != "PASS":
                failures.extend(semantic_contract["failures"])
        if path == DEFAULT_MANIFEST:
            style_contract = audit_publication_style_v3(
                pdf,
                Path(str(chapter.get("payload") or "")),
            )
            if style_contract["status"] != "PASS":
                for failure in style_contract["failures"]:
                    failures.append(
                        {
                            **failure,
                            "pattern_id": chapter.get("pattern_id"),
                        }
                    )
    quarantined = payload.get("quarantined_chapters") if isinstance(payload.get("quarantined_chapters"), list) else []
    for chapter in quarantined:
        if not isinstance(chapter, Mapping):
            continue
        previous = Path(str(chapter.get("previous_pdf") or ""))
        if previous and not previous.exists():
            failures.append({"check": "quarantine_pdf_exists", "pattern_id": chapter.get("pattern_id"), "detail": str(previous)})
        if previous:
            declared_pdfs.add(previous)
    if manifest_root.exists():
        for pdf in manifest_root.rglob("*.pdf"):
            if pdf not in declared_pdfs:
                failures.append({"check": "orphan_final_pdf", "detail": str(pdf)})
    if path == DEFAULT_MANIFEST:
        shared_content = audit_final_family_shared_content(path)
        if shared_content["status"] != "PASS":
            for failure in shared_content["failures"]:
                failures.append(
                    {
                        "check": "family_shared_recognition_content",
                        "pattern_id": ",".join(failure.get("pattern_ids", [])) or failure.get("pattern_id"),
                        "detail": f"{failure.get('family')}: {failure.get('source')}.{failure.get('field')} - {failure.get('check')}",
                    }
                )
        scanner_tradable = audit_scanner_tradable_integrity(path)
        if scanner_tradable["status"] != "PASS":
            for failure in scanner_tradable["failures"]:
                failures.append(
                    {
                        "check": "scanner_tradable_integrity",
                        "pattern_id": failure.get("pattern_id"),
                        "detail": f"{failure.get('source')}: {failure.get('check')} - {failure.get('detail')}",
                    }
                )
        entrypoint = audit_publication_entrypoints()
        if entrypoint["status"] != "PASS":
            for failure in entrypoint["failures"]:
                failures.append(
                    {
                        "check": "publication_entrypoint_guard",
                        "detail": f"{failure.get('path')}: {failure.get('check')} - {failure.get('detail')}",
                    }
                )
        preflight = _read_json(DEFAULT_TRADABLE_PREFLIGHT_MATRIX)
        if not preflight:
            failures.append({"check": "tradable_preflight_matrix_exists", "detail": str(DEFAULT_TRADABLE_PREFLIGHT_MATRIX)})
        else:
            if preflight.get("preflight_matrix_id") != TRADABLE_PREFLIGHT_MATRIX_ID:
                failures.append(
                    {
                        "check": "tradable_preflight_matrix_id",
                        "detail": f"expected {TRADABLE_PREFLIGHT_MATRIX_ID}, got {preflight.get('preflight_matrix_id')}",
                    }
                )
            preflight_ids = {
                str(row.get("pattern_id") or "")
                for row in preflight.get("chapters", [])
                if isinstance(row, Mapping)
            }
            manifest_ids = {
                str(chapter.get("pattern_id") or "")
                for chapter in chapters
                if isinstance(chapter, Mapping)
            }
            if preflight_ids != manifest_ids:
                failures.append(
                    {
                        "check": "tradable_preflight_matrix_coverage",
                        "detail": f"missing={sorted(manifest_ids - preflight_ids)} extra={sorted(preflight_ids - manifest_ids)}",
                    }
                )
            for row in preflight.get("chapters", []):
                if not isinstance(row, Mapping):
                    continue
                pattern_id = str(row.get("pattern_id") or "")
                status_value = str(row.get("preflight_status") or "")
                score = row.get("preflight_score")
                if status_value not in {
                    "preflight_strong",
                    "preflight_candidate",
                    "preflight_watchlist",
                    "preflight_weak",
                    "preflight_poor",
                    "insufficient_data",
                    "missing_event_source",
                }:
                    failures.append(
                        {
                            "check": "tradable_preflight_status",
                            "pattern_id": pattern_id,
                            "detail": status_value,
                        }
                    )
                if status_value.startswith("preflight_"):
                    try:
                        score_value = float(score)
                    except (TypeError, ValueError):
                        score_value = -1.0
                    if not (0.0 <= score_value <= 100.0):
                        failures.append(
                            {
                                "check": "tradable_preflight_score_range",
                                "pattern_id": pattern_id,
                                "detail": str(score),
                            }
                        )
        governance = _read_json(DEFAULT_CHAPTER_GOVERNANCE_MATRIX)
        if not governance:
            failures.append({"check": "chapter_governance_matrix_exists", "detail": str(DEFAULT_CHAPTER_GOVERNANCE_MATRIX)})
        else:
            if governance.get("governance_matrix_id") != DUAL_AXIS_CHAPTER_SCORING_ID:
                failures.append(
                    {
                        "check": "chapter_governance_matrix_id",
                        "detail": f"expected {DUAL_AXIS_CHAPTER_SCORING_ID}, got {governance.get('governance_matrix_id')}",
                    }
                )
            governance_ids = {
                str(row.get("pattern_id") or "")
                for row in governance.get("chapters", [])
                if isinstance(row, Mapping)
            }
            manifest_ids = {
                str(chapter.get("pattern_id") or "")
                for chapter in chapters
                if isinstance(chapter, Mapping)
            }
            if governance_ids != manifest_ids:
                failures.append(
                    {
                        "check": "chapter_governance_matrix_coverage",
                        "detail": f"missing={sorted(manifest_ids - governance_ids)} extra={sorted(governance_ids - manifest_ids)}",
                    }
                )
            for row in governance.get("chapters", []):
                if not isinstance(row, Mapping):
                    continue
                pattern_id = str(row.get("pattern_id") or "")
                if str(row.get("tradable_preflight_status") or "") == "":
                    failures.append(
                        {
                            "check": "chapter_governance_preflight_status",
                            "pattern_id": pattern_id,
                            "detail": "missing preflight status in governance row",
                        }
                    )
            for row in governance.get("chapters", []):
                if not isinstance(row, Mapping):
                    continue
                pattern_id = str(row.get("pattern_id") or "")
                tradable_status = str(row.get("tradable_status") or "")
                tradable_score_available = bool(row.get("tradable_score_available"))
                if tradable_status == "tradable_final_95":
                    score = row.get("tradable_score")
                    try:
                        score_value = float(score)
                    except (TypeError, ValueError):
                        score_value = -1.0
                    if not tradable_score_available or score_value < 95.0:
                        failures.append(
                            {
                                "check": "chapter_governance_tradable_95_score",
                                "pattern_id": pattern_id,
                                "detail": str(score),
                            }
                        )
                if tradable_status == "not_tested" and tradable_score_available:
                    failures.append(
                        {
                            "check": "chapter_governance_not_tested_score",
                            "pattern_id": pattern_id,
                            "detail": "not_tested chapter must not expose a tradable score",
                        }
                    )
        calibration = _read_json(DEFAULT_TARGET_CALIBRATION_SUMMARY)
        if not calibration:
            failures.append({"check": "target_calibration_audit_exists", "detail": str(DEFAULT_TARGET_CALIBRATION_SUMMARY)})
        else:
            if calibration.get("audit_id") != TARGET_CALIBRATION_AUDIT_ID:
                failures.append(
                    {
                        "check": "target_calibration_audit_id",
                        "detail": f"expected {TARGET_CALIBRATION_AUDIT_ID}, got {calibration.get('audit_id')}",
                    }
                )
            if str(calibration.get("status") or "").upper() != "PASS":
                failures.append({"check": "target_calibration_audit_status", "detail": str(calibration.get("status"))})
            if int(calibration.get("needs_source_extraction_count") or 0) != 0:
                failures.append(
                    {
                        "check": "target_calibration_source_extraction",
                        "detail": str(calibration.get("needs_source_extraction_count")),
                    }
                )
            calibration_ids = {
                str(row.get("pattern_id") or "")
                for row in calibration.get("rows", [])
                if isinstance(row, Mapping)
            }
            missing = sorted(
                str(chapter.get("pattern_id") or "")
                for chapter in chapters
                if str(chapter.get("pattern_id") or "") not in calibration_ids
            )
            if missing:
                failures.append({"check": "target_calibration_chapter_coverage", "detail": ", ".join(missing)})
    return {
        "status": "PASS" if not failures else "FAIL",
        "manifest": str(path),
        "final_count": len(chapters),
        "quarantine_count": len(quarantined),
        "failures": failures,
    }


def main() -> None:
    parser = argparse.ArgumentParser(description="Validate final chapters manifest.")
    parser.add_argument("--manifest", default=str(DEFAULT_MANIFEST))
    args = parser.parse_args()
    report = validate_final_manifest(Path(args.manifest))
    print(json.dumps(report, ensure_ascii=False, indent=2))
    if report["status"] != "PASS":
        raise SystemExit(1)


if __name__ == "__main__":
    main()
